language: java
jdk:
    - openjdk7
    - oraclejdk8
before_install:
    - cp ./settings.xml ~/.m2/
    - cp ./settings-arquillian.xml ~/
    - cp ./onFailure.sh  ~/
    - cp ./onSuccess.sh  ~/
    - cp ./logging.properties  ~/
    - chmod 777 ~/onFailure.sh
    - chmod 777 ~/onSuccess.sh
script:
    - mvn -B clean verify cobertura:cobertura coveralls:cobertura -Dorg.apache.maven.user-settings=~/settings-arquillian.xml -Dorg.apache.maven.global-settings=~/settings-arquillian.xml
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
notifications:
    email: false
    irc:
        channels:
            - chat.freenode.net#lightblue
    on_success: always
env:
    global:
        - secure: mAWutxKEo77AoRrH7v9HmDIfqAMBcMxAVNWEYnYuTIPywbWe2gBkov+muiLtd3E0F8maYo2BMerwkINtXy6p5gc3i1uTu9QWtFxglfPhTOJKZpIkbeUL5ryoMTKfQHYelOeW+KsIfALtO/jhmOnogwqpf6oq2qie/Zo7I4hEI4k=
        - secure: ixCk6VB0FgOSbaniVOFGLIgK1TAZc9pXAuAC7zHLcfRd00QP/9IxnQnmTN5QBQq231/A8QRaaRMFfz56ylI/igftNDoh7iYoUyOgYFbEJAS9ZUZ81j7Zp0MQojuEps/7z5ZS2FM54dlMXGXW05mO3tEeE0H+cJavEY6OznwXLTU=
